  export const GET_ERROR = "GET_ERROR"

  //SUBCATEGORY
  export const GET_ALL_SUBCATEGORY = "GET_ALL_SUBCATEGORY"

  export const CREATE_SUBCATEGORY = "CREATE_SUBCATEGORY"
  export const DELETE_SUBCATEGORY = "DELETE_SUBCATEGORY"
  export const GET_ONE_SUBCATEGORY ="GET_ONE_SUBCATEGORY"
  export const UPDATE_SUBCATEGORY ="UPDATE_SUBCATEGORY"


  




  




  //CATEGORY
  export const GET_ALL_CATEGORY = "GET_ALL_CATEGORY"
  export const CREATE_CATEGORY = "CREATE_CATEGORY"
  export const  DELETE_CATEGORY = "DELETE_CATEGORY"
  export const UPDATE_CATEGORY = "UPDATE_CATEGORY"
  export const GET_ONE_CATEGORY = "GET_ONE_CATEGORY"




  
//BRANDS
  export const GET_ALL_BRANDS = "GET_ALL_BRANDS"
  export const ADD_BRANDS = "ADD_BRANDS"
  
  export const DELETE_BRANDS = "DELETE_BRANDS"
  
  export const EDIT_BRANDS = "EDIT_BRANDS"

  export const GET_ONE_BRAND  = "GET_ONE_BRAND"



  

  





