  export const GET_ALL_CATEGORY = "GET_ALL_CATEGORY"
  export const GET_ERROR = "GET_ERROR"
  export const GET_ALL_SUBCATEGORY = "GET_ALL_SUBCATEGORY"

  export const CREATE_CATEGORY = "CREATE_CATEGORY"

  export const  DELETE_CATEGORY = "DELETE_CATEGORY"
  

  export const UPDATE_CATEGORY = "UPDATE_CATEGORY"

  export const GET_ALL_BRANDS = "GET_ALL_BRANDS"




